language: php

dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - master
  - hhvm
env:
  - 'PHPUNIT=true'
  
# Cache Composer deps
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest" PHPUNIT=true'
    - name: phpstan
      php: 7.1
      env: 'PHPSTAN=true'
  allow_failures:
    - php: master
  fast_finish: true

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - if [[ $PHPSTAN ]]; then composer require --dev phpstan/phpstan-shim --no-interaction --prefer-dist; fi

script:
  - if [[ $PHPSTAN ]]; then vendor/bin/phpstan analyse -l 3 src; fi
  - if [[ $PHPUNIT ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [[ $PHPUNIT ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
